spring:
  application:
    name: digital-business-card
  datasource:
    url: jdbc:postgresql://localhost:5432/dbcdb
    username: postgres
    password: wiris.123
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    schemas: dbcdb
    user: postgres
    password: wiris.123

  logging:
    file:
      name: ./logs/log-file.log

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

server:
  servlet: 
    context-path: /digital-business-card/api
  port: 8080